XRDDEV-1311
nordic-institute/X-Road-Security-Server-sidecar pull request #37
Opened 2020-11-05 16:54 UTC by bertofl90

2020-11-13 10:06 UTC, iluwatar requested changes

2020-11-13 10:06 UTC, iluwatar commented on doc/README.md
> +Operational monitoring for the Security Server Sidecar provider can be used to obtain information about the services it is running. The operational monitoring processes operational statistics (such a
I would link to operational monitoring protocol documents instead https://github.com/nordic-institute/X-Road/tree/develop/doc/OperationalMonitoring/Protocols to obtain information how to call them.

2020-11-13 10:14 UTC, bertofl90 commented on doc/README.md
> +1.3    | &lt;http port&gt;                         | http port, recommended &lt;ui-port&gt; +1
It's the port for allowing http request instead of https, 
"httpport=$(($2 + 1))" we have this line fron the beginning in the setup of the sidecar.
I normally use this port for the request

2020-11-13 15:10 UTC, bertofl90 commented on doc/README.md
> +We can manually backup the data stored in the "Mountpoint" every period of time.
I've added a new section for the automated backups

2020-11-16 10:17 UTC, bertofl90 commented on doc/README.md
> +
I've added the deployment options similar to this https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ig-cs_x-road_6_central_server_installation_guide.md#annex-c-deployment-options

2020-11-19 13:42 UTC, iluwatar requested changes

2020-11-19 13:42 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +The Security Server sidecar installation requires an existing X-Road Central server installed and configured and a installation of Docker.
Duplicated in `README.md`

2020-11-19 13:42 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +1.17   |                                           | Public IP address, NAT address for security server sidecar
Duplicated in `README.md`

2020-11-19 13:42 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +- if the security server has a private IP address, a corresponding NAT record must be created in the firewall (**reference data: 1.18**).
Duplicated in `README.md`

2020-11-19 13:42 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +  - Replace 'initctl' for 'supervisorctl' in 'xroad_restore.sh' for start and stop the services.
Duplicated in `README.md`

2020-11-19 13:42 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +- The external database has been tested both for external PostgreSQL database running i1n our local machine, in a remote server or inside another docker container. It also could be integrated with AW
Duplicated in `README.md`

2020-11-19 13:42 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +  ```
Duplicated in `README.md`

2020-11-26 16:39 UTC, bertofl90 commented on doc/security_server_sidecar_user_guide.md
> +  - Replace 'initctl' for 'supervisorctl' in 'xroad_restore.sh' for start and stop the services.
the installation is not exactly the same, because here is described using the setup script and in the user manual is described using directly the docker run command

2020-11-26 16:41 UTC, bertofl90 commented on doc/security_server_sidecar_user_guide.md
> +1.17   |                                           | Public IP address, NAT address for security server sidecar
The reference data is not exactly the same since i've added some new references

2020-11-27 07:11 UTC, iluwatar requested changes
There are conflicts with the `master` branch

2020-11-27 07:37 UTC, iluwatar requested changes
Make `README.md` contain only the essential information and link to the user guide for more details.

2020-11-27 07:44 UTC, iluwatar requested changes

2020-11-27 07:44 UTC, iluwatar commented on README.md
> +### 1.7 Estimated time for new Security Server Sidecar Installation
This information could be stored in Confluence instead

2020-11-27 07:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +### 2.2.4
title missing

2020-11-27 07:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +1.17   |                                           | Public IP address, NAT address for security server sidecar
So we have two sets of data, isn't that even worse?

2020-11-27 07:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +  - Replace 'initctl' for 'supervisorctl' in 'xroad_restore.sh' for start and stop the services.
Does the end user need them both?

2020-11-30 10:07 UTC, bertofl90 commented on doc/security_server_sidecar_user_guide.md
> +  - Replace 'initctl' for 'supervisorctl' in 'xroad_restore.sh' for start and stop the services.
i put both in the user guide because i guess using the setup script is more simple but probably in some scenarios you don't wanto to download the project and build the image on your local

2020-11-30 10:28 UTC, bertofl90 commented on README.md
> +### 1.7 Estimated time for new Security Server Sidecar Installation
i've put this section here: https://confluence.niis.org/display/XRDDEV/Sidecar+Installation+and+Configuration even so this documentation is out of date

2020-12-02 11:44 UTC, iluwatar requested changes

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +# Security Server Sidecar Installation User Guide <!-- omit in toc -->
```suggestion
# Security Server Sidecar User Guide <!-- omit in toc -->
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> + 13.11.2020 | 1.0     | Initial version                                                 |
Author missing

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +The intended audience of this Installation Guide are X-Road Security server system administrators responsible for installing and using X-Road Security Server Sidecar software.
```suggestion
The intended audience of this User Guide are X-Road Security server system administrators responsible for installing and using X-Road Security Server Sidecar software.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +The document is intended for readers with a moderate knowledge of Linux server management, computer networks, docker and X-Road.
```suggestion
The document is intended for readers with a moderate knowledge of Linux server management, computer networks, Docker and X-Road.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +The Security Server sidecar installation requires an existing X-Road Central server installed and configured and a installation of Docker.
```suggestion
The Security Server sidecar installation requires an existing X-Road Central server installed and configured and an installation of Docker.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +To install X-Road Security Server sidecar we can run the script setup_security_server_sidecar.sh wich will build and run the image or we can run directly one of the public images published on Dockerh
```suggestion
To install X-Road Security Server sidecar we can run the script `setup_security_server_sidecar.sh` which will build and run the image. Alternatively one of the images published on Dockerhub can be used. Both methods result in the same running container.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +To install the Security Server sidecar in a local development environment, run the script setup_security_server_sidecar.sh providing the parameters in the order shown (reference data in user guide 1.
```suggestion
To install the Security Server sidecar in a local development environment, run the script `setup_security_server_sidecar.sh` providing the parameters in the order shown (reference data in user guide 1.1, 1.2, 1.3, 1.4):
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +- Create a docker bridge-type network called xroad-network to provide container-to-container communication.
```suggestion
- Create a Docker bridge-type network called xroad-network to provide container-to-container communication.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +  - Downloads and installs the packages xroad-proxy, xroad-addon-metaservices, xroad-addon-wsdlvalidator and xroad-autologin from the public NIIS artifactory repository (version bionic-6.22.0 or late
Earlier we said that 6.23 and 6.24 are supported

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +  - Replace 'initctl' for 'supervisorctl' in 'xroad_restore.sh' for start and stop the services.
```suggestion
  - Replace `initctl` for `supervisorctl` in `xroad_restore.sh` for start and stop the services.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +To install the Security Server Sidecar slim, modify the docker image build path in the setup_security_server_sidecar.sh script by changing the path "sidecar/Dockerfile" to "sidecar/slim/Dockerfile".
```suggestion
To install the Security Server Sidecar slim, modify the Docker image build path in the setup_security_server_sidecar.sh script by changing the path `sidecar/Dockerfile` to `sidecar/slim/Dockerfile`. The Sidecar is a slim version of the sidecar who does not include support for message logging and monitoring.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +To install the Security Server Sidecar slim with Finnish settings, modify the docker image build path in the setup_security_server_sidecar.sh script by changing the path "sidecar/Dockerfile" to "side
```suggestion
To install the Security Server Sidecar slim with Finnish settings, modify the Docker image build path in the `setup_security_server_sidecar.sh` script by changing the path `sidecar/Dockerfile` to `sidecar/slim/fi/Dockerfile`
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +First, create a docker network to allow communication between containers, we can run the docker command:
```suggestion
First, create a Docker network to allow communication between containers, we can run the Docker command:
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +To install the Security Server sidecar in a local development environment, we can run the docker command:
```suggestion
To install the Security Server sidecar in a local development environment, we can run the Docker command:
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +It is possible to configure the security server sidecar to use a remote database, instead of the default locally installed one. To do that, you need to provide the remote database server hostname (&l
```suggestion
It is possible to configure the security server sidecar to use a remote database, instead of the default locally installed one. To do that, you need to provide the remote database server hostname (&lt;database-host&gt;) and port number (&lt;database-port&gt; ) as parameters when running `docker build` command. Before running the script, you must also set the environment variable `XROAD_DB_PASSWORD` with the remote database administrator master password.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +The user for the connection will be the default database user "postgres". The following configuration is needed on the remote database server to allow external access to the remote PostgreSQL databas
```suggestion
The user for the connection will be the default database user `postgres`. The following configuration is needed on the remote database server to allow external access to the remote PostgreSQL database from the security server sidecar:
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +- If the database is in your local machine you have to use the interface ip that uses the host to connect to the docker containers. You can check this ip by running "docker inspect container_name" an
```suggestion
- If the database is in your local machine you have to use the interface ip that uses the host to connect to the docker containers. You can check this ip by running `docker inspect <container_name>` and checking the gateway property.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +- The external database has been tested both for external PostgreSQL database running i1n our local machine, in a remote server or inside another docker container. It also could be integrated with AW
```suggestion
- The external database has been tested both for external PostgreSQL database running in our local machine, in a remote server or inside another Docker container. It also could be integrated with AWS RDS, it has been tested for PostgreSQL engine and Aurora PostgreSQL engine, both with version 10 of the PostgreSQL database.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +It is possible to change the external database after the initialization while the Sidecar container is running. This will not recreate the database, so we need to make sure that the 'serverconf' data
```suggestion
It is possible to change the external database after the initialization while the Sidecar container is running. This will not recreate the database, so we need to make sure that the `serverconf` database and a user with granted permissions to access it are already created. To change the database host we need to:
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +  If other components like 'message_log' or 'op_monitor' are also configured in the `etc/xroad/db.properties` file to use an external database, we must change their properties in the same way as in t
```suggestion
  If other components like 'message_log' or 'op_monitor' are also configured in the `etc/xroad/db.properties` file to use an external database, we must change their properties in the same way as in the example above.
```
```suggestion
  If other components like `message_log` or `op_monitor` are also configured in the `etc/xroad/db.properties` file to use an external database, we must change their properties in the same way as in the example above.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> + If we are using the regular version of the Security Server sidecar with the admin users for the 'messagelog' and 'op-monitor' databases we must the the same for this admin users.
```suggestion
 If we are using the regular version of the Security Server sidecar with the admin users for the `messagelog` and `op-monitor` databases we must the the same for this admin users.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +  It is possible to configure the Security Server Sidecar to adjust the logging level so that it is less verbose. To do this, we must set the environment variable XROAD_LOG_LEVEL, the value of this v
Which one is it, Security Server Sidecar or security server sidecar? Use the same format everywhere.

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +The installation is successful if docker image is running, the system services are started inside the container and the user interface is responding.
```suggestion
The installation is successful if Docker image is running, the system services are started inside the container and the user interface is responding.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +- Ensure that the security server user interface at https://SECURITYSERVER:&lt;ui port&gt;/ (**reference data: 1.3**) can be opened in a Web browser. To log in, use the account name and password chos
```suggestion
- Ensure that the security server user interface at https://SECURITYSERVER:&lt;ui port&gt;/ (**reference data: 1.3**) can be opened in a web browser. To log in, use the account name and password chosen during the installation (**reference data: 1.5; 1.6**). While the user interface is still starting up, the web browser may display a connection refused -error.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +ATTENTION: Reference items 2.1 - 2.3 in the reference data are provided to the security server owner by the X-Road central’s administrator.
```suggestion
ATTENTION: Reference items 2.1 - 2.3 in the reference data are provided to the security server owner by the X-Road central server's administrator.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +in a Web browser (**reference data: 1.2**). To log in, use the account name and password chosen during the installation (**reference data: 1.5; 1.6 **).
```suggestion
in a web browser (**reference data: 1.2**). To log in, use the account name and password chosen during the installation (**reference data: 1.5; 1.6 **).
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +After the Security Server sidecar it's configured, we need to register it in the central server, information about how to configure the Security Server sidecar on the central server can be found on t
```suggestion
After the Security Server sidecar is configured, we need to register it in the central server, information about how to configure the Security Server sidecar on the central server can be found on the  [Security Server user guide.](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#31-configuring-the-signing-key-and-certificate-for-the-security-server-owner)
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +It is possible store this configuration outside the docker container using docker volumes. Adding a docker volume will allow to keep the configuration even if the container is removed and the possibi
```suggestion
It is possible store this configuration outside the Docker container using Docker volumes. Adding a Docker volume will allow to keep the configuration even if the container is removed and the possibility to use the same configuration in other Docker containers.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +To add the docker volume, in the docker run command [docker run command](##2.6-Installation) add the docker volume parameter mapping to the config folder:
```suggestion
To add the Docker volume, in the Docker run command [docker run command](##2.6-Installation) add the Docker volume parameter mapping to the config folder:
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +Once the docker container is running we can see the volume information and where it is stored in our local machine by running the following command:
```suggestion
Once the Docker container is running we can see the volume information and where it is stored in our local machine by running the following command:
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +By default the Security Server backs up its configuration automatically once every day. Backups older than 30 days are automatically removed from the server. If needed, the automatic backup policies
```suggestion
By default the Security Server backs up its configuration automatically once every day. Backups older than 30 days are automatically removed from the server. If needed, the automatic backup policies can be adjusted by editing the `/etc/cron.d/xroad-proxy` file.
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +Automatic backups will be stored in the folder '/var/lib/xroad/backup/'. We can create a volume for store the automatic backups by adding in the run command:
```suggestion
Automatic backups will be stored in the folder `/var/lib/xroad/backup/`. We can create a volume for store the automatic backups by adding in the run command:
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +armin
remove

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +From the docker run command [docker run command](##2.6-Installation) add the docker volume parameter mapping to the host local storage folder for the logs:
```suggestion
From the Docker run command [docker run command](##2.6-Installation) add the docker volume parameter mapping to the host local storage folder for the logs:
```

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +X-Road Security Server Sidecar has multiple deployment options.  The simplest choice is to have a single security server with local database. This is usually fine for majority of the cases, but there
database running inside the container or database running on the same host?

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +![Security server with local database](img/ig-ss_local_db.svg)
there is a typo in the picture

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +The simplest deployment option is to use a single security server sidecar with local database. For development and testing purposes there is rarely need for anything else, but for production the requ
same comment as above

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +It is possible to use a remote database with X-Road Security Server Sidecar. This option is sometimes used in development and testing when there's need to externalize the database state.
Isn't this the most common option?

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +
External load balancing scenario is missing

2020-12-02 11:44 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +
Did we mention somewhere that AWS EKS is supported?

2020-12-02 12:07 UTC, bertofl90 commented on doc/security_server_sidecar_user_guide.md
> +X-Road Security Server Sidecar has multiple deployment options.  The simplest choice is to have a single security server with local database. This is usually fine for majority of the cases, but there
inside the container, i will make it clear

2020-12-03 06:16 UTC, iluwatar commented
Let me know when it's ready for review again

2020-12-03 10:18 UTC, iluwatar commented on README.md
> +
It's still there

2020-12-03 11:25 UTC, raulmartinez-leadin requested changes

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +    For adding volume support we have to modify the docker run sentence inside the setup_security_server_sidecar.sh script and add the volume support:
```suggestion
    To add volume support we have to modify the docker run command inside the setup_security_server_sidecar.sh script by adding the following parameters:
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +- Ensure that the security server user interface at https://SECURITYSERVER:&lt;ui port&gt;/ (**reference data: 1.3**) can be opened in a Web browser. To log in, use the account name and password chos
```suggestion
- Ensure that the Security Server user interface at https://SECURITYSERVER:&lt;ui port&gt;/ (**reference data: 1.3**) can be opened in a Web browser. To log in, use the account name and password chosen during the installation (**reference data: 1.5; 1.6**). While the user interface is still starting up, the Web browser may display a connection refused -error.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +During the security server initial configuration, the server’s X-Road membership information and the software token’s PIN are set
```suggestion
During the Security Server initial configuration, the server’s X-Road membership information and the software token’s PIN are set
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +Configuring the security server assumes that the security server owner is a member of the X-Road.
```suggestion
Configuring the Security Server assumes that the Security Server owner is a member of the X-Road.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +2.2    | 	<security server owner's member class> *E.g.*  *GOV-government*; *COM - commercial*             | Member class of the security server's owner
```suggestion
2.2    | 	<Security Server owner's member class> *E.g.*  *GOV-government*; *COM - commercial*             | Member class of the Security Server's owner
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +2.3    | &lt;security server owner register code&gt;              | Member code of the security server's owner
```suggestion
2.3    | &lt;Security Server owner register code&gt;              | Member code of the Security Server's owner
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +2.4    | &lt;choose security server identificator name&gt;        | Security server's code
```suggestion
2.4    | &lt;choose Security Server identificator name&gt;        | Security Server's code
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +Note (1): The global configuration provider's download URL and TCP port 80 must be reachable from the security server sidecar network.
```suggestion
Note (1): The global configuration provider's download URL and TCP port 80 must be reachable from the Security Server sidecar network.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +Note (2): Reference items 2.1 - 2.3 are provided to the security server owner by the X-Road central server's administrator.
```suggestion
Note (2): Reference items 2.1 - 2.3 are provided to the Security Server owner by the X-Road Central Server's administrator.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +Note (3): The security server member code usually refers to the organization's business code, although there can be other conventions depending on the X-Road governing authority's rules.
```suggestion
Note (3): The Security Server member code usually refers to the organization's business code, although there can be other conventions depending on the X-Road governing authority's rules.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +Note (4): The security server code uniquely identifies the security server in an X-Road instance. X-Road instance's governing authority may dictate rules how the code should be chosen.
```suggestion
Note (4): The Security Server code uniquely identifies the security server in an X-Road instance. X-Road instance's governing authority may dictate rules on how the code should be chosen.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> + - The security server owner’s member class (**reference data: 2.2**).
```suggestion
 - The Security Server owner’s member class (**reference data: 2.2**).
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> + - The security server owner’s member code (**reference data: 2.3**).
```suggestion
 - The Security Server owner’s member code (**reference data: 2.3**).
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> + If the member class and member code are correctly entered, the system displays the security server owner’s name as registered in the X-Road center.
```suggestion
 If the member class and member code are correctly entered, the system displays the Security Server owner’s name as registered in the X-Road Central Server.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> + - Security server code (**reference data: 2.4**), which is chosen by the security server administrator and which has to be unique across all the security servers belonging to the same X-Road member.
```suggestion
 - Security Server code (**reference data: 2.4**), which is chosen by the Security Server administrator and which has to be unique across all the Security Servers belonging to the same X-Road member.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +After the Security Server sidecar it's configured, we need to register it in the central server, information about how to configure the Security Server sidecar on the central server can be found on t
```suggestion
After the Security Server sidecar it's configured, we need to register it in the Central Server, information about how to configure the Security Server sidecar on the Central Server can be found on the  [Security Server user guide.](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#31-configuring-the-signing-key-and-certificate-for-the-security-server-owner)
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +Operational monitoring for the Security Server Sidecar provider can be used to obtain information about the services it is running. The operational monitoring processes operational statistics (such a
```suggestion
Operational monitoring for the Security Server Sidecar provider can be used to obtain information about the services it is running. The operational monitoring processes operational statistics (such as which services have been called, how many times, what was the size of the response, etc.) of the Security Servers. The operational monitoring will create a database named "op-monitor" for store the data, this database can be configured internally in the container or externally (check 1.6). More information about how to test it can be found here https://github.com/nordic-institute/X-Road/tree/develop/doc/OperationalMonitoring/Protocols
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +The purpose of the message log is to provide means to prove the reception of a regular request or response message to a third party. Messages exchanged between security servers are signed and encrypt
```suggestion
The purpose of the message log is to provide means to prove the reception of a regular request or response message to a third party. Messages exchanged between Security Servers are signed and encrypted. For every regular request and response, the Security Server produces a complete signed and timestamped document (Associated Signature Container).
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +In case of synchronous timestamping, the timestamping is an integral part of the message exchange process (one timestamp is taken for the request and another for the response). If the timestamping fa
```suggestion
For the case of synchronous timestamping, the timestamping is an integral part of the message exchange process (one timestamp is taken for the request and another for the response). If the timestamping fails, the message exchange fails as well and the Security Server responds with an error message.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +In case of asynchronous timestamping, all the messages (maximum limit is determined in the configuration stored in the message log since the last periodical timestamping event are timestamped with a
```suggestion
For the case of asynchronous timestamping, all the messages (maximum limit is determined in the configuration stored in the message log) exchanged since the last periodical timestamping event are timestamped with a single (batch) timestamp. By default, the Security Server uses asynchronous timestamping for better performance and availability.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +X-Road Security Server Sidecar has multiple deployment options.  The simplest choice is to have a single security server with local database. This is usually fine for majority of the cases, but there
```suggestion
X-Road Security Server sidecar has multiple deployment options. The simplest choice is to have a single Security Server with a local database. This is usually fine for the majority of the cases. Nevertheless, there are other Security Server images available that can be used for tailoring the deployment to specific needs. These different images could be combined. Any of these Security Server sidecar images can be used either as a consumer or provider role.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +The simplest deployment option is to use a single security server sidecar with local database inside the container. For development and testing purposes there is rarely need for anything else, but fo
```suggestion
The simplest deployment option is to use a single Security Server sidecar container with the local database running inside the container. For development and testing purposes there is rarely the need for anything else. However, for running the Security Server sidecar on a production environment, the requirements may be stricter.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +In production systems it's rarely acceptable to have a single point of failure. Security server supports provider side high availability setup via so called internal load balancing mechanism. The set
```suggestion
In production systems, it's rarely acceptable to have a single point of failure. Security Server supports provider side high-availability setup via the so-called internal load balancing mechanism. The setup works so that the same combination of <member>/<member class>/<member code>/<subsystem>/<service code> is configured on multiple Security Servers and X-Road will then route the request to the server that responds the fastest. Note that this deployment option does not provide performance benefits, just redundancy.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +In this example we are going to create a secret for the X-Road Security Server Sidecar environment variables with sensitive data.
```suggestion
In this example, we are going to create a secret for the X-Road Security Server sidecar environment variables with sensitive data.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +X-Road Security Server Sidecar supports a variety of cloud databases including AWS RDS and Azure Database for PostgreSQL. This deployment option is useful when doing development in cloud environment,
```suggestion
X-Road Security Server sidecar supports a variety of cloud databases including AWS RDS and Azure Database for PostgreSQL. This deployment option is useful when doing development in a cloud environment, where the use of a cloud-native database is the first choice.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +It is possible to use a remote database with X-Road Security Server Sidecar.
```suggestion
It is possible to use a remote database with X-Road Security Server sidecar.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +In a different scenario where the Sidecar would take a long time to start, the startup probe can be used in combination with the liveness probe, so that it waits until the startup probe has succeeded
```suggestion
In a different scenario where the sidecar container would take a long time to start, the startup probe can be used in combination with the liveness probe, so that it waits until the startup probe has succeeded before starting the liveness probe. The tricky part is to set up a startup probe with the same command, HTTP or TCP check, with a failureThreshold * periodSeconds long enough to cover the worse case startup time.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +Create a manifest file called for example "secret-env-variables.yaml" and fill it with the desired values of the environment variables.
```suggestion
- Create a manifest file called for example 'secret-env-variables.yaml' and fill it with the desired values of the environment variables.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +- replace <namespace_name> with the name of the namespace if it's different from `default`. If we want to use `default` namespace, we can delete the line.
```suggestion
- Replace <namespace_name> with the name of the namespace if it's different from `default`. If we want to use `default` namespace, we can delete the line.
```

2020-12-03 11:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_user_guide.md
> +Apply the manifest:
```suggestion
- Apply the manifest:
```

2020-12-03 14:58 UTC, bertofl90 commented on doc/security_server_sidecar_user_guide.md
> +  It is possible to configure the Security Server Sidecar to adjust the logging level so that it is less verbose. To do this, we must set the environment variable XROAD_LOG_LEVEL, the value of this v
i've replace all using uppercase

2020-12-09 09:56 UTC, iluwatar approved these changes

2020-12-09 10:06 UTC, raulmartinez-leadin approved these changes

2020-12-09 10:06 UTC, merged