XRDDEV-1386 Disable messagelog archival process on the secondary nodes
nordic-institute/X-Road-Security-Server-sidecar pull request #45
Opened 2020-12-31 12:43 UTC by bertofl90

2021-01-04 07:07 UTC, raulmartinez-leadin commented on sidecar/files/balancer-secondary-entrypoint.sh
> +
These two lines would probably benefit from a comment

2021-01-04 07:07 UTC, raulmartinez-leadin commented on sidecar/files/balancer-slim-secondary-entrypoint.sh
> +crudini --set /etc/xroad/conf.d/local.ini message-log archive-interval '0 * * ? * * 2099' &&
These two lines would probably benefit from a comment

2021-01-04 07:07 UTC, raulmartinez-leadin commented on sidecar/files/balancer-slim-secondary-entrypoint.sh
> -echo "* * * * * root rsync -e 'ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5' -avz --timeout=10 --delete-delay  --exclude "/conf.d/node.ini" --exclude "*.tmp"  --delay-updates --log-file=/var/l
I would insert a couple of line breaks

2021-01-04 07:07 UTC, raulmartinez-leadin commented on sidecar/files/balancer-secondary-entrypoint.sh
> +echo "* * * * * root rsync -e 'ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5' -avz --timeout=10 --delete-delay  --exclude "/conf.d/node.ini" --exclude "*.tmp"  --delay-updates --log-file=/var/l
I would insert a couple of line breaks

2021-01-07 08:05 UTC, raulmartinez-leadin requested changes

2021-01-07 08:05 UTC, raulmartinez-leadin commented on sidecar/files/balancer-secondary-entrypoint.sh
> + #Add to the cron job the synchronizaction with primary pod and updates archive-interval and clean-interval properties in the file /etc/xroad/conf.d/local.ini setting a long time interval for disable
Typo in synchronizaction -> synchronization

2021-01-07 08:05 UTC, raulmartinez-leadin commented on sidecar/files/balancer-secondary-entrypoint.sh
> +#Add to the cron job the synchronizaction with primary pod and updates archive-interval and clean-interval properties in the file /etc/xroad/conf.d/local.ini setting a long time interval for disable
Typo in synchronizaction -> synchronization

2021-01-07 08:05 UTC, raulmartinez-leadin commented on sidecar/files/balancer-slim-secondary-entrypoint.sh
> + #Synchronize with primary pod and updates archive-interval and clean-interval properties in the file /etc/xroad/conf.d/local.ini setting a long time interval for disable the archive of messagelogs i
Perhaps copy and paste this comment into others so that they have exactly the same wording for consistency reasons (others start with "Add to the cron job the synchronization with primary pod...")

2021-01-07 08:05 UTC, raulmartinez-leadin commented on sidecar/files/balancer-slim-secondary-entrypoint.sh
> +crudini --set /etc/xroad/conf.d/local.ini message-log archive-interval '0 * * ? * * 2099' &&
These two lines would probably benefit from a comment

2021-01-07 08:05 UTC, raulmartinez-leadin commented on sidecar/files/balancer-secondary-entrypoint.sh
> +crudini --set /etc/xroad/conf.d/local.ini message-log archive-interval '0 * * ? * * 2099' &&
These two lines would probably benefit from a comment

2021-01-13 09:33 UTC, bertofl90 commented on sidecar/files/balancer-slim-secondary-entrypoint.sh
> + #Synchronize with primary pod and updates archive-interval and clean-interval properties in the file /etc/xroad/conf.d/local.ini setting a long time interval for disable the archive of messagelogs i
because it's slightly different, one is a file that will be run by a cron job, the other is running at initialization

2021-01-14 07:42 UTC, raulmartinez-leadin approved these changes

2021-01-18 12:25 UTC, merged