Xrddev 1419 Kubernetes Documentation
nordic-institute/X-Road-Security-Server-sidecar pull request #46
Opened 2021-01-12 16:59 UTC by bertofl90

2021-01-22 10:47 UTC, iluwatar commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +   * [4.2 Installation Instructions](#42-installation-instructions)
Chapter numbering seems to be bit off... after 4.4 should come 4.5

2021-01-28 07:59 UTC, raulmartinez-leadin requested changes

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +List the PVC by running (The PVC status should be boud, it means that the claim is attached to a PV):
```suggestion
List the PVC by running (The PVC status should be bound, which means that the PVC is attached to a PV):
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +kubectl delete -f /path/to/file.yaml.
```suggestion
kubectl delete -f /path/to/file_name.yaml.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +To mount the volume on a Pod, it is required to have a PVC bounded to a PV, then modify the Pod manifest, in this case the manifest defined in the step [2.1 Single Pod Deployment with internal databa
```suggestion
To mount the volume to a Pod, we should make sure to have a PVC bounded to a PV and modify the Pod manifest, for example, the manifest defined in the step [2.1 Single Pod Deployment with internal database](#21-single-pod-deployment-with-internal-database), by mapping the volume to the xroad configuration `etc/xroad` as follows (**reference data: 3.4, 3.12, 3.13**):
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +When you mount a volume to a pod, by default it always gets mounted with the permission of root:root.
```suggestion
When mounting a volume to a Pod, by default it always gets mounted with the permission of root:root.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +This could be a problem when mapping the volume to local folders like the configuration folder `etc/xroad` or the message-log backup `var/lib/xroad` that requires xroad:xroad (UID: 999, GID:999) perm
```suggestion
This could be a problem when the volume is mapped to local paths such as `etc/xroad` or `var/lib/xroad`, which both require xroad:xroad (UID: 999, GID:999) permission.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +Kubernetes allow us to deploy the container as another user using Security Context, but this doesn't work because Security Server Sidecar requires to be run by the root user.
```suggestion
Kubernetes allows deploying the container as another non-root user using Security Context configuration. However, this approach is not yet possible since the Security Server Sidecar requires to be run by the root user.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +It is possible to change manually the permission setting the UID and GID in the folder of the Cluster node instance where the volume is mounted.
```suggestion
A possible solution is to change manually the permissions by setting the UID and GID in the folder of the Cluster node instance where the volume is mounted.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +Another possible is use Kubernetes Init Containers for setting the permissions to the volume folder, wich launches before the main container. An example for change the permissions to the `etc/xroad`
```suggestion
Another possible solution is to use Kubernetes Init Containers for setting the correct permissions to the volume folder which launches before the main container. Below is an example configuration for changing the permissions to the `etc/xroad` volume folder (**reference data: 3.4, 3.13**):
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +Note (1) References: https://stackoverflow.com/questions/43544370/kubernetes-how-to-set-volumemount-user-group-and-file-permissions
```suggestion
Note (1) References: [StackOverflow](https://stackoverflow.com/questions/43544370/kubernetes-how-to-set-volumemount-user-group-and-file-permissions)
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +                     https://serverfault.com/questions/906083/how-to-mount-volume-with-specific-uid-in-kubernetes-pod
```suggestion
                     [Serverfault](https://serverfault.com/questions/906083/how-to-mount-volume-with-specific-uid-in-kubernetes-pod)
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +- Create a manifest file called for example 'secret-env-variables.yaml' and fill it with the desired values of the environment variables ( **reference Data: 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10**):
```suggestion
- Create a manifest file called for example 'secret-env-variables.yaml' and fill it with the desired values of the environment variables ( **reference Data: 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10, 3.1**):
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +The Secrets that store keys can be consumed in a similar way to volumes, for this you will have to include the Secret in the definition of volumes within the Pod deployment manifest, select the key a
```suggestion
The Secrets that store keys can be consumed in a similar way to volumes. To do this, you will have to include the Secret in the definition of volumes within the Pod deployment manifest, select the key and assign permissions to it, then mount the volume in a folder on the container (**reference Data: 3.13, 3.14**):
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +- A Persitent Volume Claim bounded to a Persitent Volume for store the Primary Pod configuration [4.2.3 Kubernetes Volumes](#423-Kubernetes-volumes).
```suggestion
- A Persistent Volume Claim is bounded to a Persistent Volume to store the Primary Pod configuration [4.2.3 Kubernetes Volumes](#423-Kubernetes-volumes).
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +- A Kubernetes Secret with a ssh key pair stored [4.2.4 Kubernetes Secrets](#424-Kubernetes-secrets).
```suggestion
- A Kubernetes Secret with an ssh key pair is stored [4.2.4 Kubernetes Secrets](#424-Kubernetes-secrets).
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +This service has no open port since is not required any communication from outside.
```suggestion
This service has no open ports since it does not require any communication to or from the outside.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +The Pod defines two volumes, one for store the secret public key described in [4.2.4 Kubernetes Secrets](#424-Kubernetes-secrets) and a volume to store the `etc/xroad` configuration. It is possible t
```suggestion
The Pod defines two volumes: one volume to store the secret public key described in [4.2.4 Kubernetes Secrets](#424-Kubernetes-secrets), and a second volume to store the `etc/xroad` configuration. It is possible to choose between the volumes described in [4.2.3 Kubernetes Volumes](#423-Kubernetes-volumes).
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +Once the configuration is ready, it is possible to verify by running a Healthcheck from inside the internal network, checking that the result is OK:
```suggestion
Once the configuration is ready, it is possible to verify the installation by running a Healthcheck to the Pod running the Security Server Sidecar container from the internal network and checking that the result is OK:
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +An example of how to install the Secondary Pod is shown in the manifest below (**reference Data: 3.1, 3.3, 3.4, 3.12, 3.13, 3.14,3.15, 3.17, 3.18, 3.19, 3.20, 1.4, 1.5, 1.6, 1.10**):
```suggestion
An example of how to install the Secondary Pod is shown in the manifest below (**reference Data: 3.1, 3.2, 3.4, 3.12, 3.13, 3.14, 3.15, 3.17, 3.18, 3.19, 3.20, 1.4, 1.5, 1.6, 1.10**):
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +- An NLB (Network Load Balancer) which will be in charge of redirecting the traffic between the different Secondary pods. The ClusterIP property is optional and is used to assign a fixed private IP t
```suggestion
- An NLB (Network Load Balancer) which will be in charge of redirecting the traffic between the different Secondary pods. The ClusterIP property is optional and is used to assign a fixed private IP to the Load Balancer, this can help you in the configuration of the Security Server Sidecar at the central server. If the ClusterIP is not assigned, a new private IP will be assigned to the Load Balancer in each deployment.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +It has the required ports "5500" "5577" for the messages communication between Security Servers open.
```suggestion
It has the required ports "5500" and "5577" to exchange messages between Security Servers open.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +- A DeploymentControll for deploy the "n" numbers of Pods with the image for the Secondary Pods, as image tag we can choose between the "secondary" or "secondary-slim" described in [3 X-Road Security
```suggestion
- A DeploymentControl for deploying the "n" numbers of Pods with the image for the Secondary Pods. As image tag, we can choose between the "secondary" or "secondary-slim" described in [3 X-Road Security Server Sidecar images for Kubernetes](#3-x-road-security-server-sidecar-images-for-Kubernetes).
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +The Pods have one volume for store the public and private ssh keys defined on [4.2.4 Kubernetes Secrets](#424-Kubernetes-secrets) require for the synchronization with the Primary Pod via ssh.
```suggestion
The Pods have one volume to store the public and private ssh keys defined on [4.2.4 Kubernetes Secrets](#424-Kubernetes-secrets) which are required for the synchronization with the Primary Pod via ssh.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +It is not required to add a new volume for store the configuration since all the secondary Pods synchronize the configuration with the Primary, but could be use to make sure that all the Secondary Po
```suggestion
It is not required to add a new volume to store the Secondary Pod configuration, since all the secondary Pods synchronize the configuration with the Primary, but it could be useful to make sure that all the Secondary Pods have the same configuration in case any of them fail to synchronize.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +After the manifest is deployed we can scale the Secondary Pods by running:
Reference data missing

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +The backup system of the Security Servers described [here](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#13-back-up-and-restore)  is
```suggestion
The backup system of the Security Servers described in the [User Guide](https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#13-back-up-and-restore) is also valid for the installation using Kubernetes.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +- AWS Elastic Block Store: Backups can be stored by creating a snapshot of the volume from the AWS admin UI, these snapshots can be configured automatically also it is possible to restore the snapsho
```suggestion
- AWS Elastic Block Store: Backups can be stored by creating a snapshot of the volume from the AWS admin UI. These snapshots can be configured automatically and it is possible to restore the snapshots into the volume.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +For more information about Cloudwatch check [here](https://docs.aws.amazon.com/cloudwatch/index.html).
```suggestion
For more information about CloudWatch check the [Amazon CloudWatch documentation](https://docs.aws.amazon.com/cloudwatch/index.html).
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +**CloudWatch container insights** is a tool available for AWS EKS that we can use to  collect, aggregate, and summarize metrics and logs from your containerized applications and microservices.
```suggestion
**CloudWatch container insights** is a tool available for AWS EKS that we can use to collect, aggregate, and summarize metrics and logs from your containerized applications and microservices.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +It will be possible to update the version of the Security Server Sidecar by re-displaying the image with a higher version in the image tag.
```suggestion
It is possible to update the version of the Security Server Sidecar by re-deploying the image with a higher version in the image tag.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +In case of the scenario [2.3 Multiple Pods using a Load Balancer](#23-multiple-pods-using-a-load-balancer) and it is required to no disrupt the connection while the version is updating, it is require
```suggestion
In case of the scenario [2.3 Multiple Pods using a Load Balancer](#23-multiple-pods-using-a-load-balancer), if we do not want to disrupt the connection during the version update, it is required to take several steps:
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +- First, it is required to stop in the Secondary Pods, the cron job service that handles synchronization with the Primary Pod, it is possible to do that by running in a console for each Secondary Pod
```suggestion
- First, we should stop the cron job service running in the Secondary Pods that handles synchronization with the Primary Pod by running in a console for each Secondary Pod (**reference Data: 3.2**):
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +- Update the Primary Pod by open a shell for the Primary Pod container by running:
```suggestion
- Update the Primary Pod by opening a Shell to the Primary Pod container by running:
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +- Once the Primary Pod is update, it is necessary to do the same previous step for all the Secondary Pods one by one, doing this, each Secondary Pod will remain in "NotReady" state and will exit the
```suggestion
- Once the Primary Pod is updated, it is necessary to do the same previous step for all the Secondary Pods one by one. While doing this, each Secondary Pod will remain in "NotReady" state and will exit the Load Balancer redirect until it is updated, but the rest will continue to work without disrupting the connection.
```

2021-01-28 07:59 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +It is also recommend to send the logs inside the volume to a AWS S3 Bucket. For doing that it is required to:
```suggestion
It is also recommended to send the logs inside the volume to an AWS S3 Bucket. To do that we need to:
```

2021-02-05 07:48 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +| Price | General Purpose SSD(gp2) Volumes:  $0.10 per GB-month of provisioned storage.EBS Snapchots: $0.05 per GB-month of data stored. | Standard Storage (GB-Month) : $0.30. |
This is still pending

2021-02-09 07:52 UTC, raulmartinez-leadin approved these changes

2021-02-09 09:36 UTC, merged