XRDDEV-1312
nordic-institute/X-Road-Security-Server-sidecar pull request #51
Opened 2021-02-05 07:45 UTC by raulmartinez-leadin

Security Server Sidecar security documentation.

2021-02-09 11:43 UTC, bertofl90 requested changes

2021-02-09 11:43 UTC, bertofl90 commented on doc/security_server_sidecar_security_guide.md
> +Note that the backup does not include X-Road admin user account(s) or `/etc/xroad.properties` (database admin credentials; needed when using a remote database). You need to take care of moving these
Maybe some links or references of how to set the admin users

2021-02-19 07:25 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_security_guide.md
> +Before deploying the Security Server Sidecar, it is strongly recommended to use the [Docker Bench for Security tool](https://github.com/docker/docker-bench-security) for securing the Docker host Oper
Added link to CIS Docker Benchmark.

2021-02-19 07:26 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_security_guide.md
> +The Docker daemon runs with root privileges, so it is important to audit all Docker related files and directories in addition to Linux file system and system calls. The Docker Daemon depends on some
Added link to auditd man page https://linux.die.net/man/8/auditd

2021-02-19 07:28 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_security_guide.md
> +Auditing can potentially generate large log files, so make sure those audit logs are rotated and archived periodically. It is recommended to have a separate partition created for audit logs to avoid
Added description of log files directory and auditd.conf man page https://linux.die.net/man/8/auditd.conf. Added clarification for creating a separate partition for log directory.

2021-02-19 07:30 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_security_guide.md
> +
Added example and clarification of how to set CPU shares limit.

2021-02-19 07:30 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_security_guide.md
> +
Added example and clarification of how to set PIDs limit.

2021-02-19 07:31 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_security_guide.md
> +During the Security Server Sidecar installation, the user should supply the different database and admin UI credentials as well as the software token PIN code, among other parameters, so that the con
Added reference data section.

2021-02-19 07:31 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_security_guide.md
> +However, when deploying the Security Server Sidecar in a production environment, we can make use of Secrets to avoid passing this information as plain text on a command line interface. More informati
Fixed link to Kubernetes user guide.

2021-02-19 07:32 UTC, raulmartinez-leadin commented on doc/security_server_sidecar_security_guide.md
> +Note that the backup does not include X-Road admin user account(s) or `/etc/xroad.properties` (database admin credentials; needed when using a remote database). You need to take care of moving these
Added clarification and link to user guide documentation.

2021-02-22 09:57 UTC, bertofl90 commented on doc/security_server_sidecar_security_guide.md
> +However, when deploying the Security Server Sidecar in a production environment, we can make use of Secrets to avoid passing this information as plain text on a command line interface. More informati
The link should point to master

2021-02-22 11:28 UTC, bertofl90 approved these changes

2021-02-22 11:30 UTC, merged