XRDDEV-1600 example templates
nordic-institute/X-Road-Security-Server-sidecar pull request #58
Opened 2021-03-04 16:30 UTC by bertofl90

2021-03-08 12:03 UTC, raulmartinez-leadin requested changes

2021-03-08 12:03 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +The [load_balancer_setup](/files/load_balancer_setup.yaml) contains all the necessary Kubernetes objects to setup the scenario [2.3 Multiple Pods using a Load Balancer](#23-multiple-pods-using-a-load
```suggestion
The [load_balancer_setup manifest template](/files/load_balancer_setup.yaml) contains all the necessary Kubernetes objects to set up the scenario [2.3 Multiple Pods using a Load Balancer](#23-multiple-pods-using-a-load-balancer). The namespace where the objects are deployed is `sidecar`.
```

2021-03-15 22:02 UTC, raulmartinez-leadin requested changes

2021-03-15 22:02 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +  + &lt;public key base64> Public key encoding in base64, we can get it by running: `path/to/id_rsa.pub|base64 -w0`.
```suggestion
  + &lt;public key base64&gt; Public key encoding in base64, we can get it by running: `path/to/id_rsa.pub|base64 -w0`.
```

2021-03-15 22:02 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +  + &lt;private key base64> Private key encoding in base64, we can get it by running: `path/to/id_rsa|base64 -w0`.
```suggestion
  + &lt;private key base64&gt; Private key encoding in base64, we can get it by running: `path/to/id_rsa|base64 -w0`.
```

2021-03-16 10:40 UTC, bertofl90 commented on doc/files/load_balancer_setup.yaml
> +  clusterIP: 10.100.217.185
removed!

2021-03-22 08:06 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +4. Verify that the secrets are deployed:
```suggestion
4. Verify that the secrets are deployed:

```

2021-03-22 08:06 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +```
```suggestion
```

```

2021-03-22 08:06 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +5. Verify that the services are created:
```suggestion
5. Verify that the services are created:

```

2021-03-22 08:06 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +6. Verify that the Primary and Secondary Pods are deployed. The Secondary Pod should remain in the "Not Ready" state until the Primary Pod is configured. If we are using a volume that already has the
```suggestion
6. Verify that the Primary and Secondary Pods are deployed. The Secondary Pod should remain in the "Not Ready" state until the Primary Pod is configured. If we are using a volume that already has the Primary Pod configuration, the Secondary Pod should switch to the "Ready" state after approximately 3-4 minutes.

```

2021-03-22 08:06 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +7. Delete all the objects by running:
```suggestion
7. Delete all the objects by running:

```

2021-03-22 08:06 UTC, raulmartinez-leadin commented on doc/kubernetes_security_server_sidecar_user_guide.md
> +kubectl delete -f load_balancer_setup.yaml"
```suggestion
kubectl delete -f load_balancer_setup.yaml
```

```

2021-03-22 16:31 UTC, raulmartinez-leadin approved these changes

2021-03-22 16:31 UTC, merged