XRDDEV-1818
nordic-institute/X-Road-Security-Server-sidecar pull request #73
Opened 2021-11-03 09:10 UTC by jhyoty

2021-11-16 12:43 UTC, iluwatar requested changes

2021-11-16 12:43 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +In production use, either persistent volumes should be used. Using a separate database is recommended.
But there are the optional parameters, right? Maybe this part should be rephrased a bit.

2021-11-16 12:43 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +In production use, either persistent volumes should be used. Using a separate database is recommended.
Perhaps link to chapter 2.7

2021-11-16 12:43 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +* If the old container was ephemeral, it is necessary to manually map the volumes (can not use --volumes-from)
What does it mean here that the container is ephemeral? Is it just that the old container didn't use volumes for the data?

2021-11-16 12:43 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +  ... published ports and other parameters, e.g network ...
Does it mean that every parameter that was given for the old container has to be given also here?

2021-11-16 12:43 UTC, iluwatar commented on doc/security_server_sidecar_user_guide.md
> +it is necessary to verity that the `/etc/xroad.properties` file has been correctly populated (see [IG-SS, Appendix D](#Ref_IG-SS) for details).
```suggestion
it is necessary to verify that the `/etc/xroad.properties` file has been correctly populated (see [IG-SS, Annex D](#Ref_IG-SS) for details).
```

2021-11-16 13:04 UTC, jhyoty commented on doc/security_server_sidecar_user_guide.md
> +  ... published ports and other parameters, e.g network ...
We are starting a new container, and most parameters need to be given again (some environment parameters like database address are persisted in the x-road configuration so those could be omitted).

2021-11-16 13:04 UTC, jhyoty commented on doc/security_server_sidecar_user_guide.md
> +* If the old container was ephemeral, it is necessary to manually map the volumes (can not use --volumes-from)
If the container was started with `--rm` parameter, it is removed when it stops and --volumes-from does not work.

2021-11-16 13:04 UTC, jhyoty commented on doc/security_server_sidecar_user_guide.md
> +In production use, either persistent volumes should be used. Using a separate database is recommended.
Perhaps, but I think this is good enough.

2021-11-23 12:58 UTC, iluwatar approved these changes

2021-11-23 12:59 UTC, merged